version: '3'

services:
  todoback:
    build: ./todo-app/back-end
    ports:
      - 3001:3001
    restart: always
  todofront:
    build: ./todo-app/front-end
    environment:
      - REACT_APP_API_HOST=todoback
    depends_on:
      - "todoback"
    ports:
      - 3000:3000
  todotests:
    build: ./todo-app/tests
    depends_on:
      - "todoback"
      - "todofront"
    environment:
      - FRONT_HOST=todofront